.TH BTREE-DUMP 1 "August 1999" Fastresolve
.SH NAME
btree-dump \- unformatted dump of a B-Tree DB file
.SH SYNOPSIS
.B btree-dump
btree-file.db
.SH DESCRIPTION
.B btree-dump
reads a B-Tree DB 2.x file, such as those produced by
.B dns-terror
or
.BR getdominfo .
It prints the key-value mappings.
.SH "SEE ALSO"
convert-dom-db(1), convert-ip-db(1), dns-terror(1), getdominfo(1)
.SH AUTHORS
David MacKenzie <djm@djmnet.org>.
Please send comments and bug reports to <fastresolve-bugs@djmnet.org>.
